// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/curso": {
            "get": {
                "description": "get cursos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "curso"
                ],
                "summary": "Devuelve todos los carritos de la base de datos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/curso/{curso_id}/comentarios": {
            "get": {
                "description": "get comentarios",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "curso"
                ],
                "summary": "Obtiene comentarios de un curso",
                "parameters": [
                    {
                        "type": "string",
                        "description": "671989c45e52cd33c7e3f6cd",
                        "name": "curso_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "add comentarios",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "curso"
                ],
                "summary": "Agrega comentario a un curso",
                "parameters": [
                    {
                        "type": "string",
                        "description": "671989c45e52cd33c7e3f6cd",
                        "name": "curso_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "671989c45e52cd33c7e3f6cd",
                        "name": "curso_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateComentarioRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.CreateComentarioRequest": {
            "type": "object",
            "required": [
                "detalle",
                "dislikes",
                "fecha",
                "id_curso",
                "likes",
                "nombre",
                "titulo"
            ],
            "properties": {
                "detalle": {
                    "type": "string"
                },
                "dislikes": {
                    "type": "integer"
                },
                "fecha": {
                    "type": "string"
                },
                "id_curso": {
                    "type": "string"
                },
                "likes": {
                    "type": "integer"
                },
                "nombre": {
                    "type": "string"
                },
                "titulo": {
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
