definitions:
  model.Material:
    properties:
      nombre:
        type: string
      tipo:
        type: string
      url:
        type: string
    type: object
  request.ClaseRequest:
    properties:
      descripcion:
        type: string
      indice_clase:
        type: integer
      material_adicional:
        items:
          $ref: '#/definitions/model.Material'
        type: array
      nombre_clase:
        type: string
      video:
        type: string
    required:
    - descripcion
    - indice_clase
    - nombre_clase
    - video
    type: object
  request.CreateComentarioClase:
    properties:
      detalle:
        type: string
      dislikes:
        type: integer
      fecha:
        type: string
      id_clase:
        type: string
      likes:
        type: integer
      nombre:
        type: string
      titulo:
        type: string
    required:
    - detalle
    - fecha
    - id_clase
    - nombre
    - titulo
    type: object
  request.CreateCursoRequest:
    properties:
      cantidad_usuarios:
        minimum: 0
        type: integer
      descripcion:
        type: string
      imagen_banner:
        type: string
      imagen_miniatura:
        type: string
      nombre:
        type: string
      unidades:
        items:
          $ref: '#/definitions/request.UnidadRequest'
        type: array
      valoracion:
        maximum: 5
        minimum: 0
        type: number
    required:
    - descripcion
    - imagen_banner
    - imagen_miniatura
    - nombre
    - unidades
    type: object
  request.UnidadRequest:
    properties:
      clases:
        items:
          $ref: '#/definitions/request.ClaseRequest'
        type: array
      indice_unidad:
        type: integer
      nombre_unidad:
        type: string
    required:
    - clases
    - indice_unidad
    - nombre_unidad
    type: object
  response.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
  response.ResponseUnidad:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /clase/{clase_id}:
    get:
      consumes:
      - application/json
      description: comentario clase
      parameters:
      - description: clase ID
        in: path
        name: clase_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Devuelve una comentario clase
      tags:
      - clase
  /clase/{id}:
    get:
      consumes:
      - application/json
      description: Devuelve una clase
      parameters:
      - description: CLASE ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: get clase por Object ID
      tags:
      - clase
  /clase/comentarios:
    post:
      consumes:
      - application/json
      description: crea un comentario para una clase
      parameters:
      - description: json del comentario
        in: body
        name: cometario
        required: true
        schema:
          $ref: '#/definitions/request.CreateComentarioClase'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Crea un comentario
      tags:
      - clase
  /curso:
    get:
      consumes:
      - application/json
      description: get cursos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Devuelve todos los cursos de la base de datos
      tags:
      - curso
    post:
      consumes:
      - application/json
      description: crea un curso con todos sus componentes
      parameters:
      - description: json del curso
        in: body
        name: curso
        required: true
        schema:
          $ref: '#/definitions/request.CreateCursoRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Crea un curso
      tags:
      - curso
  /curso/{curso_id}:
    get:
      consumes:
      - application/json
      description: get curso a partir del ID
      parameters:
      - description: curso id
        in: path
        name: curso_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Devuelve un curso
      tags:
      - curso
  /curso/{curso_id}/comentarios:
    get:
      consumes:
      - application/json
      description: get comentarios
      parameters:
      - description: id del curso
        in: path
        name: curso_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Obtiene comentarios de un curso
      tags:
      - curso
    post:
      consumes:
      - application/json
      description: add comentarios
      parameters:
      - description: id del curso
        in: path
        name: curso_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Agrega comentario a un curso
      tags:
      - curso
  /ruta-para-rellenar-base:
    get:
      description: crear cursos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Crea cursos con todos sus componentes (rellena la base)
      tags:
      - BaseDatos
  /unidad:
    get:
      description: get unidades
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Devuelve todos las unidades de la base de datos
      tags:
      - unidad
  /unidad/{curso_id}:
    get:
      consumes:
      - application/json
      description: Encontrar una unidad con el id de un curso
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseUnidad'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Devuelve todos las unidades que pertenezcan a un respectivo Curso
      tags:
      - unidad
  /unidad/{unidad_id}/clases:
    get:
      consumes:
      - application/json
      description: Devuelve todas las clases que tiene una unidad
      parameters:
      - description: UNIDAD OBJECT ID
        in: path
        name: id_unidad
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: get clases por unidad
      tags:
      - unidad
swagger: "2.0"
