definitions:
  request.CreateComentarioRequest:
    properties:
      detalle:
        type: string
      dislikes:
        type: integer
      fecha:
        type: string
      id_curso:
        type: string
      likes:
        type: integer
      nombre:
        type: string
      titulo:
        type: string
    required:
    - detalle
    - dislikes
    - fecha
    - id_curso
    - likes
    - nombre
    - titulo
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
  response.ResponseUnidad:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /curso:
    get:
      consumes:
      - application/json
      description: get cursos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Devuelve todos los carritos de la base de datos
      tags:
      - curso
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
swagger: "2.0"
